base_model: Qwen/Qwen2.5-7B-Instruct
tokenizer_type: AutoTokenizer

# # LoRA configuration
# adapter: lora
# lora_model_dir:
# lora_r: 32
# lora_alpha: 64
# lora_dropout: 0.05
# lora_target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"] # for Qwen models
# lora_fan_in_fan_out:
# lora_bias: none

# Quantization (optional but recommended for memory efficiency)
load_in_8bit: false # or false if you prefer 4bit
load_in_4bit: false
strict: false

val_set_size: 0.1

device_map: "auto"

datasets:
  - path: data/splits_ft_vs_ppi/ft_train_800/ft_train/ft_train_data.jsonl
    type: chat_template
    chat_template: tokenizer_default
    field_system: system
    field_messages: conversations
    message_field_role: role
    message_field_content: content
    message_property_mappings:
      content: content

dataset_prepared_path: outputs/models/qwen_800/last_run_prepared
output_dir: outputs/models/qwen_800

sequence_len: 1024
sample_packing: false
pad_to_sequence_len: false
eval_sample_packing: false

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_torch_8bit
lr_scheduler: cosine
learning_rate: 1e-5

bf16: auto
tf32: false

gradient_checkpointing: true
resume_from_checkpoint:
logging_steps: 1
flash_attention: false

warmup_steps: 800
saves_per_epoch: 4
weight_decay: 0.001
special_tokens:
evals_per_epoch: 3

seed: 42
