base_model: mistralai/Mistral-7B-Instruct-v0.3
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

val_set_size: 0.1

device_map: "auto"

datasets:
  - path: data/atp/human_train.chat.jsonl
    type: chat_template
    chat_template: tokenizer_default
    field_system: system
    field_messages: conversations
    message_field_role: role
    message_field_content: content
    message_property_mappings:
      content: content

dataset_prepared_path: outputs/models/mistral/last_run_prepared
output_dir: outputs/models/mistral

sequence_len: 1024
sample_packing: false
pad_to_sequence_len: false
eval_sample_packing: false

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 3
num_epochs: 1
optimizer: adamw_torch_8bit
lr_scheduler: cosine
learning_rate: 1e-5

bf16: auto
tf32: false

gradient_checkpointing: true
resume_from_checkpoint:
logging_steps: 1
flash_attention: false

warmup_steps: 800
saves_per_epoch: 4
weight_decay: 0.001
special_tokens:
evals_per_epoch: 3

seed: 42
